---

- name: Create PostgreSQL database
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"
    encoding: "{{ encoding | default('UTF-8') }}"
    owner: "{{ owner | default('postgres') }}"

- name: Create PostgreSQL user
  become_user: postgres
  postgresql_user:
    name: "{{ db_username }}"
    password: "{{ db_password }}"

- name: Ensure access to database
  become_user: postgres
  postgresql_privs:
    db: "{{ db_name }}"
    role: "{{ db_username }}"
    objs: ALL_IN_SCHEMA
    privs: ALL
  when: db_name is defined
