---

- name: Create PostgreSQL user
  become_user: postgres
  postgresql_user:
    name: "{{ db_username }}"
    password: "{{ db_password }}"

- name: Ensure access to database
  become_user: postgres
  postgresql_privs:
    db: "{{ db_name }}"
    role: "{{ db_username }}"
    objs: ALL_IN_SCHEMA
    privs: ALL
  when: db_name is defined
