---

- name: Populate database
  become_user: postgres
  shell: "for i in {{ path }}/{{ item }}; do cat $i | psql tpcc ; done"
  loop:
    - createtable.sql
    - createindex.sql
    - sequence.sql
    - neworder01
    - delivery01
    - payment01
    - orderstatus01
    - stocklevel01