---

- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    ################### MODIFY VARIABLES HERE ######################
    gcp_region: us-east1
    gcp_project: tpc-c-222411
    bucket: 'storage-tcp-c'
    #################################################################

    gcp_cred_kind: serviceaccount
    gcp_cred_file: '~/.gcloud/credentials-tpc-c.json'

  roles:
    # Create VM instances
    - role: instances
      vars:
        gcp_zone: us-east1-b
        gcp_machine_type: n1-standard-4
        source_image: projects/centos-cloud/global/images/centos-7-v20181113
        disk_type: pd-ssd
        disk_size: 64
        disks:
          - disk-01
        addresses:
          - addr-01
        instances:
          - { index: 1, tag: benchmark }

    # Create storage bucket
    #- role: storage