plugin: gcp_compute
projects:
  - project_id
zones:
  - us-east1-b
filters:
  # - machineType = n1-standard-1
  # - name = shard-03

keyed_groups:
  - prefix: ''
    separator: ''
    key: tags['items']

auth_kind: serviceaccount
service_account_file: "~/.gcloud/credentials-tpc-c.json"