- hosts: all
  become: yes 
  vars:
    ############### MODIFY VARIABLES AS NEEDED ###############
    bucket: 'storage-tcp-c'
    gs_access_key: 'GOOG7LPNDJF3TYHFGMMTKMBD'
    gs_secret_key: 'cbA50GCTXbYyp4XsIaSmlW7UFKyuI+cqJLXRyL8p'
    dump_file: '{{ path }}/tpcc-100-warehouses.dump'
    db_name: 'tpcc'

    # Workload properties:
    number_warehouses: 80
    measurement_time: 10
    number_clients_wharehouse: 7
    think_time: true
    ##########################################################

    path: "/home/postgres/tpc-c-0.1-SNAPSHOT"
    workload_file: "{{ path }}/etc/workload-config.properties"

  roles:
    # Download dump_file from storage
    #- role: download-storage
    #  vars:
    #    object: "{{ dump_file }}"
    #    dest: "{{ path }}/{{ dump_file }}"

    # Change workload properties
    - role: workload-config

    # Drop database
    - role: drop-db

    # Create database
    - role: create-db

    # Restore database
    - role: restore-db

    # Run benchmark
    - role: run

    # Upload results to storage
    - role: upload-run